// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as $$String from "bs-platform/lib/es6/string.js";

function makeBaseStyle(param) {
  return Css.style(/* :: */[
              Css.backgroundColor(Css.hex("2c3e50")),
              /* :: */[
                Css.border(Css.px(2), Css.solid, Css.hex("2c3e50")),
                /* :: */[
                  Css.borderRadius(Css.rem(0.25)),
                  /* :: */[
                    Css.fontSize(Css.rem(0.8)),
                    /* :: */[
                      Css.padding3(Css.rem(0.1), Css.rem(0.45), Css.rem(0.2)),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

function makeStatusStyle(status) {
  switch (status) {
    case "info" :
        return Css.style(/* :: */[
                    Css.backgroundColor(Css.hex("3498db")),
                    /* [] */0
                  ]);
    case "pending" :
        return Css.style(/* :: */[
                    Css.backgroundColor(Css.rgba(241, 196, 15, 0.15)),
                    /* :: */[
                      Css.borderColor(Css.rgba(241, 196, 15, 0.8)),
                      /* :: */[
                        Css.selector("&:hover", /* :: */[
                              Css.backgroundColor(Css.rgba(241, 196, 15, 0.15)),
                              /* :: */[
                                Css.borderColor(Css.rgba(241, 196, 15, 0.8)),
                                /* [] */0
                              ]
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]);
    case "WIP" :
    case "graveyard" :
    case "loved" :
    case "qualified" :
    case "ranked" :
        return "hello to you too!";
    default:
      return "Nice to meet you!";
  }
}

function Badge(Props, _children) {
  var status = Props.status;
  return React.createElement("span", {
              className: status
            }, $$String.capitalize(status));
}

var make = Badge;

export {
  makeBaseStyle ,
  makeStatusStyle ,
  make ,
  
}
/* Css Not a pure module */
