// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("CheckBox");

var checkBox = Css.style(/* :: */[
      Css.borderRadius(Css.px(2)),
      /* :: */[
        Css.color(Css.black),
        /* :: */[
          Css.width(Css.px(20)),
          /* :: */[
            Css.height(Css.px(20)),
            /* [] */0
          ]
        ]
      ]
    ]);

function make(checked, disabled, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("input", {
                          className: checkBox,
                          checked: checked,
                          disabled: disabled,
                          type: "checkbox"
                        });
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  checkBox ,
  make ,
  
}
/* component Not a pure module */
