// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";

function checkBoxStyle(color, activeColor) {
  return Css.style(/* :: */[
              Css.unsafe("-webkit-appearance", "none"),
              /* :: */[
                Css.margin2(Css.auto, Css.rem(1)),
                /* :: */[
                  Css.width(Css.px(20)),
                  /* :: */[
                    Css.height(Css.px(20)),
                    /* :: */[
                      Css.border(Css.px(1), Css.solid, Css.hex(color)),
                      /* :: */[
                        Css.borderRadius(Css.px(2)),
                        /* :: */[
                          Css.verticalAlign(Css.middle),
                          /* :: */[
                            Css.backgroundColor(Css.transparent),
                            /* :: */[
                              Css.selector("&:checked", /* :: */[
                                    Css.borderColor(Css.hex(activeColor)),
                                    /* :: */[
                                      Css.backgroundColor(Css.hex(activeColor)),
                                      /* [] */0
                                    ]
                                  ]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

function Checkbox(Props, _children) {
  var checked = Props.checked;
  var disabled = Props.disabled;
  var color = Props.color;
  var activeColor = Props.activeColor;
  return React.createElement("input", {
              className: checkBoxStyle(color, activeColor),
              checked: checked,
              disabled: disabled,
              type: "checkbox"
            });
}

var make = Checkbox;

export {
  checkBoxStyle ,
  make ,
  
}
/* Css Not a pure module */
