// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function HelloReason(Props, _children) {
  var message = Props.message;
  return React.createElement("p", undefined, "Message from ReasonReact " + message);
}

var make = HelloReason;

export {
  make ,
  
}
/* react Not a pure module */
