// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";

function makeStyle(strokeDashoffset) {
  return Css.style(/* :: */[
              Css.transition(350, undefined, undefined, "stroke-dashoffset"),
              /* :: */[
                Css.transform(Css.rotate(Css.deg(-90))),
                /* :: */[
                  Css.transformOrigin(Css.pct(50), Css.pct(50)),
                  /* :: */[
                    Css.unsafe("stroke-dashoffset", strokeDashoffset),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

function floatToString(prim) {
  return prim.toString();
}

function ProgressRing(Props, _children) {
  var radius = Props.radius;
  var stroke = Props.stroke;
  var progress = Props.progress;
  Props.color;
  var normalizedRadius = radius - stroke * 2;
  var circumference = normalizedRadius * 2 * Math.PI;
  var strokeDashoffset = (circumference - progress / 100 * circumference).toString();
  var size = (radius * 2).toString();
  return React.createElement("svg", {
              style: {
                margin: "0"
              },
              height: size,
              width: size
            }, React.createElement("circle", {
                  className: makeStyle(strokeDashoffset),
                  cx: radius.toString(),
                  cy: radius.toString(),
                  fill: "transparent",
                  r: normalizedRadius.toString(),
                  stroke: "white",
                  strokeDasharray: "" + (String(circumference) + (" " + (String(circumference) + ""))),
                  strokeWidth: stroke.toString()
                }));
}

var make = ProgressRing;

export {
  makeStyle ,
  floatToString ,
  make ,
  
}
/* Css Not a pure module */
