// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

function makeStyle(param) {
  return Css.style(/* :: */[
              Css.transition(350, undefined, undefined, "stroke-dashoffset"),
              /* :: */[
                Css.transform(Css.rotate(Css.deg(-90))),
                /* :: */[
                  Css.transformOrigin(Css.pct(50), Css.pct(50)),
                  /* [] */0
                ]
              ]
            ]);
}

export {
  makeStyle ,
  
}
/* Css Not a pure module */
