// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Icon$Beatconnectclient from "../../utils/Icon.bs.js";

function makeWrapperStyle(h) {
  return Css.style(/* :: */[
              Css.unsafe("-webkit-app-region", "drag"),
              /* :: */[
                Css.backgroundColor(Css.hex("171717")),
                /* :: */[
                  Css.height(Css.px(h)),
                  /* :: */[
                    Css.width(Css.pct(100)),
                    /* :: */[
                      Css.display(/* flex */-1010954439),
                      /* :: */[
                        Css.alignItems(Css.center),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

function makeTitleStyle(param) {
  return Css.style(/* :: */[
              Css.paddingLeft(Css.px(12)),
              /* :: */[
                Css.fontSize(Css.px(12)),
                /* :: */[
                  Css.color(Css.white),
                  /* :: */[
                    Css.flex3(1, 1, Css.zero),
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

function makeControlStyle(bgColor, param) {
  return Css.style(/* :: */[
              Css.unsafe("-webkit-app-region", "no-drag"),
              /* :: */[
                Css.padding2(Css.zero, Css.px(7)),
                /* :: */[
                  Css.selector("&:hover", /* :: */[
                        Css.backgroundColor(bgColor !== undefined ? bgColor : Css.rgba(255, 255, 255, 0.15)),
                        /* [] */0
                      ]),
                  /* [] */0
                ]
              ]
            ]);
}

function TitleBar(Props, _children) {
  var title = Props.title;
  var height = Props.height;
  var onMinimizeClick = Props.onMinimizeClick;
  var onMaximizeClick = Props.onMaximizeClick;
  var onCloseClick = Props.onCloseClick;
  return React.createElement("div", {
              className: makeWrapperStyle(height)
            }, React.createElement("div", {
                  className: makeTitleStyle(/* () */0)
                }, title), React.createElement("div", {
                  className: makeControlStyle(undefined, /* () */0),
                  onClick: onMinimizeClick
                }, Icon$Beatconnectclient.make("Dash", undefined, 12, 12, /* () */0)), React.createElement("div", {
                  className: makeControlStyle(undefined, /* () */0),
                  onClick: onMaximizeClick
                }, Icon$Beatconnectclient.make("Square", undefined, 12, 12, /* () */0)), React.createElement("div", {
                  className: makeControlStyle(Css.red, /* () */0),
                  onClick: onCloseClick
                }, Icon$Beatconnectclient.make("Cancel", undefined, 12, 12, /* () */0)));
}

var make = TitleBar;

var $$default = TitleBar;

export {
  makeWrapperStyle ,
  makeTitleStyle ,
  makeControlStyle ,
  make ,
  $$default ,
  $$default as default,
  
}
/* Css Not a pure module */
