// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as RenderIcons from "./renderIcons";

function jsRenderIconsArgsToJs(param) {
  return {
          name: param[/* name */0],
          color: param[/* color */1],
          width: param[/* width */2],
          height: param[/* height */3]
        };
}

function jsRenderIconsArgsFromJs(param) {
  return /* record */[
          /* name */param.name,
          /* color */param.color,
          /* width */param.width,
          /* height */param.height
        ];
}

function jsRenderIcons(prim) {
  return RenderIcons.default(prim);
}

function make(name, color, width, height, param) {
  return RenderIcons.default(jsRenderIconsArgsToJs(/* record */[
                  /* name */name,
                  /* color */color,
                  /* width */width,
                  /* height */height
                ]));
}

export {
  jsRenderIconsArgsToJs ,
  jsRenderIconsArgsFromJs ,
  jsRenderIcons ,
  make ,
  
}
/* ./renderIcons Not a pure module */
